package FRONTEND;

import BACKEND.Gestor;
import BACKEND.Serializacao;
import BACKEND.Sistema;
import javax.swing.JOptionPane;

public class JanelaAdmGestoresAddGestores extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao dados;
    private int funcao;
    private Gestor gestor;

    public JanelaAdmGestoresAddGestores(Sistema sistema, Serializacao dados) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    public JanelaAdmGestoresAddGestores(Sistema sistema, Serializacao dados, int funcao, Gestor gestor) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.funcao = funcao;
        this.gestor = gestor;
        txtTitulo.setText("Editar Gestor");
        btnAdicionar.setText("Editar");
        txtUsername.setText(gestor.getUsername());
        txtNome.setText(gestor.getNome());
        txtPassword.setText(gestor.getPassword());
        txtPassword2.setText(gestor.getPassword());
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtConfirmar = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPassword2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(18, 30, 49));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Adicionar Gestores");
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 560, 48));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(18, 30, 49));
        jLabel4.setText("Nome");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 30, 49));
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        txtConfirmar.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        txtConfirmar.setForeground(new java.awt.Color(18, 30, 49));
        txtConfirmar.setText("Confirmar Password");
        jPanel1.add(txtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        txtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNome.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 290, 30));

        txtPassword2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txtPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 290, 30));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(18, 30, 49));
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 290, 30));

        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 290, 30));

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(18, 30, 49));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(18, 30, 49), new java.awt.Color(18, 30, 49)));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 90, 33));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(18, 30, 49));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(18, 30, 49), new java.awt.Color(18, 30, 49)));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 90, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/borda2222.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        if (txtUsername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o username do Gestor");
            txtUsername.requestFocus();
            return;
        }
        if (txtPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Introduza a password");
            txtPassword.requestFocus();
            return;
        }
        if (txtPassword2.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Introduza a verificaçao da password");
            txtPassword2.requestFocus();
            return;
        }
        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o nome do Gestor");
            txtNome.requestFocus();
            return;
        }
        String u = txtUsername.getText().trim();
        String p = new String(txtPassword.getPassword());
        String n = txtNome.getText().trim();
        if (funcao == 1) {
            gestor.setNome(n);
            gestor.setUsername(u);
            gestor.setPassword(p);
        } else {
            if (sistema.getUtilizadores().existe(txtUsername.getText())) {
                JOptionPane.showMessageDialog(this, "Ja existe um Gestor com esse codigo");
                txtUsername.requestFocus();
                return;
            }
            Gestor gestor = new Gestor(u, n, p);
            sistema.getUtilizadores().inserir(gestor);
        }
        dados.guardar(sistema);
        dispose();
        JanelaAdmListaGestores janela = new JanelaAdmListaGestores(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
        JanelaAdmListaGestores janela = new JanelaAdmListaGestores(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtConfirmar;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
