package FRONTEND;

import BACKEND.Serializacao;
import BACKEND.Sistema;
import BACKEND.Utente;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class JanelaRegisto extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao dados;

    public JanelaRegisto(Sistema sistema, Serializacao dados) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * Metodo para verficar se uma String é um email valido
     *
     * @param email
     * @return
     */
    private boolean validarEmail(String email) {
        String regex = "^(.+)@(.+)$";

        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNSNS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtMorada = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        txtLocalidade = new javax.swing.JTextField();
        txtContacto = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(3, 122, 118));
        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" REGISTO UTENTE");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 55));
        jLabel2.getAccessibleContext().setAccessibleName("  REGISTO UTENTE");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(18, 30, 49));
        jLabel4.setText("Nº Utente do SNS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtNSNS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNSNS.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(txtNSNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 182, 29));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 30, 49));
        jLabel5.setText("Nome");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(18, 30, 49));
        jLabel6.setText("Morada");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(18, 30, 49));
        jLabel7.setText("Localidade");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(18, 30, 49));
        jLabel8.setText("Contacto telefónico");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(18, 30, 49));
        jLabel9.setText("Data de Nascimento");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(18, 30, 49));
        jLabel10.setText("Email");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        txtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNome.setBorder(new javax.swing.border.MatteBorder(null));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 182, 29));

        txtMorada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMorada.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(txtMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 182, 29));

        txtDataNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDataNascimento.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(txtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 182, 29));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(18, 30, 49));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(18, 30, 49), new java.awt.Color(18, 30, 49)));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 90, 33));

        txtLocalidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLocalidade.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(txtLocalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 182, 29));

        txtContacto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContacto.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 337, 182, 30));

        btnRegistar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistar.setForeground(new java.awt.Color(18, 30, 49));
        btnRegistar.setText("Registar");
        btnRegistar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(18, 30, 49), new java.awt.Color(18, 30, 49)));
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 90, 33));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(18, 30, 49));
        jLabel11.setText("Password");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 389, 182, 30));

        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 182, 29));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/borda2222.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
        JanelaLogin janela = new JanelaLogin(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        if (txtNSNS.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o seu Nº SNS");
            txtNSNS.requestFocus();
            return;
        }
        if (txtNSNS.getText().length() != 9) {
            JOptionPane.showMessageDialog(this, "O Nº SNS tem 9 digitos");
            txtNSNS.requestFocus();
            return;
        }
        if (txtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o seu Nome");
            txtNome.requestFocus();
            return;
        }
        if (txtMorada.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a sua morada");
            txtMorada.requestFocus();
            return;
        }
        if (txtLocalidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a sua Localidade");
            txtLocalidade.requestFocus();
            return;
        }
        if (txtDataNascimento.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a sua data de nascimento");
            txtDataNascimento.requestFocus();
            return;
        }
        if (txtContacto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o seu contacto telefonico");
            txtContacto.requestFocus();
            return;
        }
        if (txtContacto.getText().length() != 9) {
            JOptionPane.showMessageDialog(this, "O contacto tem 9 digitos");
            txtContacto.requestFocus();
            return;
        }
        if (txtEmail.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o seu email");
            txtEmail.requestFocus();
            return;
        }
        if (!validarEmail(txtEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Introduza um email valido");
            txtEmail.requestFocus();
            return;
        }
        if (txtPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Introduza a sua password");
            txtPassword.requestFocus();
            return;
        }
        if (sistema.getUtilizadores().existe(txtNSNS.getText())) {
            JOptionPane.showMessageDialog(this, "Ja existe um utilizador registado com este Nº SNS");
            txtNSNS.requestFocus();
            return;
        }
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("d/MM/uuuu");
        Utente utente = new Utente(txtNSNS.getText().trim(), txtNome.getText(), new String(txtPassword.getPassword()), txtMorada.getText(), txtLocalidade.getText(), LocalDate.parse(txtDataNascimento.getText(), formatter), new Long(txtContacto.getText()), txtEmail.getText());
        sistema.getUtilizadores().inserir(utente);
        if (!sistema.autenticarUtilizador(txtNSNS.getText().trim(), new String(txtPassword.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Erro ao autenticar o utilizador");
            txtNSNS.requestFocus();
            return;
        } else {

            if (sistema.getCentros_Vacinacao().existeCentro(txtLocalidade.getText())) {
                utente.setCentro_vacinacao(sistema.getCentros_Vacinacao().getCentroPorLocalidade(txtLocalidade.getText()));
                dispose();
                JanelaUtente janela = new JanelaUtente(sistema, dados);
                //JanelaLogin janela = new JanelaLogin(sistema, dados);
                janela.setVisible(true);
            } else {
                dispose();
                JanelaEscolhaCentro janela = new JanelaEscolhaCentro(sistema, dados);
                janela.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnRegistarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLocalidade;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JTextField txtNSNS;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
