package FRONTEND;

import BACKEND.CentroVacinacao;
import BACKEND.Serializacao;
import BACKEND.Sistema;
import BACKEND.Vacina;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class JanelaAdmListaCentrosStockAlocar extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao dados;
    private CentroVacinacao centro;
    private Vacina vacina;

    public JanelaAdmListaCentrosStockAlocar(Sistema sistema, Serializacao dados, CentroVacinacao centro) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.centro = centro;
        preencherVacinas();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    public JanelaAdmListaCentrosStockAlocar(Sistema sistema, Serializacao dados, CentroVacinacao centro, Vacina vacina) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.centro = centro;
        this.vacina = vacina;
        preencherVacinas();
        comboVacinas.setSelectedItem(vacina.getNome());
        comboVacinas.setEnabled(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * Metodo para validar se uma string é um numero inteiro
     *
     * @param str
     * @return
     */
    private boolean isInteger(String str) {
        return str != null && str.matches("[0-9]*");
    }

    /**
     * Metodo listar as vacinas que existem no sistema
     */
    private void preencherVacinas() {
        ArrayList<Vacina> vacinas = sistema.getVacinas();
        for (Vacina vacina : vacinas) {
            comboVacinas.addItem(vacina.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        comboVacinas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 30, 49));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alocar Vacinas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 560, 48));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(18, 30, 49));
        jLabel8.setText("Quantidade de Vacinas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        txtQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantidade.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 340, 40));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(18, 30, 49));
        jLabel9.setText("Tipo de Vacina");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(18, 30, 49));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(18, 30, 49), new java.awt.Color(18, 30, 49)));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 80, 30));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(18, 30, 49));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(18, 30, 49), new java.awt.Color(18, 30, 49)));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 80, 30));

        comboVacinas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma vacina..." }));
        comboVacinas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(18, 30, 49)));
        jPanel1.add(comboVacinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/borda2222.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (comboVacinas.getSelectedItem().toString().equalsIgnoreCase("Selecione uma vacina...")) {
            JOptionPane.showMessageDialog(this, "Selecione uma vacina");
            return;
        }
        if (!isInteger(txtQuantidade.getText())) {
            JOptionPane.showMessageDialog(this, "A quantidade deve ser um numero inteiro");
            txtQuantidade.requestFocus();
            return;
        }
        Long quantidade = 0L;
        if (!txtQuantidade.getText().trim().isEmpty()) {
            quantidade = Long.parseLong(txtQuantidade.getText().trim());
        }
        String n_vacina = comboVacinas.getSelectedItem().toString();
        Vacina vacina_alocar = null;
        for (Vacina v : sistema.getVacinas()) {
            if (v.getNome().equals(n_vacina)) {
                vacina_alocar = v;
            }
        }
        centro.getStock_vacina().adicionarQtdVacina(vacina_alocar, quantidade);
        dispose();
        JanelaAdmListaCentrosStock janela = new JanelaAdmListaCentrosStock(sistema, dados, centro);
        janela.setVisible(true);

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
        JanelaAdmListaCentrosStock janela = new JanelaAdmListaCentrosStock(sistema, dados, centro);
        janela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboVacinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
