package FRONTEND;

import BACKEND.CentroVacinacao;
import BACKEND.Serializacao;
import BACKEND.Sistema;
import java.util.ArrayList;
import BACKEND.Gestor;
import javax.swing.JOptionPane;

public class JanelaAdmListaCentroAddCentro extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao dados;
    private int funcao;
    private CentroVacinacao centro;

    public JanelaAdmListaCentroAddCentro(Sistema sistema, Serializacao dados, int funcao, CentroVacinacao centro) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.funcao = funcao;
        this.centro = centro;
        verGestores();
        txtTitulo.setText("Editar Centros de Vacinação");
        btnAdicionar.setText("Guardar");
        txtCodigo.setText(centro.getCodigo());
        txtMorada.setText(centro.getMorada());
        txtLocalidade.setText(centro.getLocalidade());
        String cod_gestor = centro.getGestor().getUsername();
        comboGestores.addItem(cod_gestor);
        comboGestores.setSelectedItem(cod_gestor);
    }

    public JanelaAdmListaCentroAddCentro(Sistema sistema, Serializacao dados) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        verGestores();
    }

    /**
     * Metodo para listar os gestores que ainda nao tem um centro atribuido
     */
    private void verGestores() {
        ArrayList<Gestor> gestores = sistema.getUtilizadores().getGestores();
        ArrayList<Gestor> gestores_centro = sistema.getCentros_Vacinacao().verGestoresComCentro();
        for (Gestor gestor : gestores) {
            if (!gestores_centro.contains(gestor)) {
                comboGestores.addItem(gestor.getUsername());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboGestores = new javax.swing.JComboBox<>();
        btnAdicionar = new javax.swing.JButton();
        txtLocalidade = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtMorada = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(18, 30, 49));
        jLabel4.setText("Selecionar Gestor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(18, 30, 49));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Adicionar Centros Vacinação");
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 560, 48));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 30, 49));
        jLabel5.setText("Código Centro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(18, 30, 49));
        jLabel8.setText("Morada Centro");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(18, 30, 49));
        jLabel10.setText("Localidade Centro");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        comboGestores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um gestor" }));
        comboGestores.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(18, 30, 49)));
        getContentPane().add(comboGestores, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 270, 40));

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(18, 30, 49));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setToolTipText("");
        btnAdicionar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(18, 30, 49), new java.awt.Color(18, 30, 49)));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 90, 33));

        txtLocalidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtLocalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 270, 40));

        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 270, 40));

        txtMorada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 270, 40));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(18, 30, 49));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("");
        btnVoltar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(18, 30, 49), new java.awt.Color(18, 30, 49)));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 90, 33));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/borda2222.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        if (txtCodigo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza o codigo do centro");
            txtCodigo.requestFocus();
            return;
        }
        if (txtMorada.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a morada do centro");
            txtMorada.requestFocus();
            return;
        }
        if (txtLocalidade.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduza a localidade do centro");
            txtLocalidade.requestFocus();
            return;
        }
        if ((String) comboGestores.getSelectedItem() == "Selecione um gestor") {
            JOptionPane.showMessageDialog(this, "Selecione um gestor");
            return;
        }
        if (funcao == 1) {
            centro.setCodigo(txtCodigo.getText());
            centro.setMorada(txtMorada.getText());
            centro.setLocalidade(txtLocalidade.getText());
            String cod_gestor = comboGestores.getSelectedItem().toString();
            Gestor gestor = (Gestor) sistema.getUtilizadores().getUtilizador(cod_gestor);
            centro.setGestor(gestor);
            dados.guardar(sistema);
            dispose();
            JanelaAdmListaCentro janela = new JanelaAdmListaCentro(sistema, dados);
            janela.setVisible(true);
        } else {
            if (sistema.getCentros_Vacinacao().existeCentroCod(txtCodigo.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Ja existe um centro com esse codigo");
                txtCodigo.requestFocus();
                return;
            }
            String cod_gestor = comboGestores.getSelectedItem().toString();
            Gestor gestor = (Gestor) sistema.getUtilizadores().getUtilizador(cod_gestor);
            CentroVacinacao centro2 = new CentroVacinacao(txtCodigo.getText(), txtMorada.getText(), txtLocalidade.getText(), gestor);
            sistema.getCentros_Vacinacao().inserir(centro2);
            dispose();
            JanelaAdmListaCentro janela = new JanelaAdmListaCentro(sistema, dados);
            janela.setVisible(true);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
        JanelaAdmListaCentro janela = new JanelaAdmListaCentro(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboGestores;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtLocalidade;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
